version: '3.6'

services:
  web:
    image: "hkroger/measurinator-website:latest"
    build:
      context: .
    volumes:
      - ~/.ssh/:/root/.ssh
      # Can't mount everything because passenger won't start, go figure,..
      # - ./:/home/app/measurinator_website
      - ./bin/:/home/app/measurinator_website/bin/
      - ./config/:/home/app/measurinator_website/config/
      - ./app/:/home/app/measurinator_website/app/
      - ./db/:/home/app/measurinator_website/db/
      - ./lib/:/home/app/measurinator_website/lib/
      - ./test/:/home/app/measurinator_website/test/
      - ./public/:/home/app/measurinator_website/public/
      - ./script/:/home/app/measurinator_website/script/
      - ./doc/:/home/app/measurinator_website/doc/
      # Mounting vendor is causing some weird shit
      # - ./vendor/:/home/app/measurinator_website/vendor/
      - ./log/:/home/app/measurinator_website/log/
      - ./tmp/:/home/app/measurinator_website/tmp/
      - ./.bundle/:/home/app/measurinator_website/.bundle
      - ./.sass-cache/:/home/app/measurinator_website/.sass-cache
      - ./Gemfile:/home/app/measurinator_website/Gemfile
      - ./Gemfile.lock:/home/app/measurinator_website/Gemfile.lock
    ports:
      - "3000:80"
    environment:
      RAILS_ENV: "development"
      DB_HOSTS: "docker.for.mac.localhost"
