development:
  hosts:
    - 192.168.10.3
    - 192.168.10.133
    - 127.0.0.1
  keyspace: 'temperatures'

production:
  hosts:
    - 192.168.0.22
    - 192.168.0.23
    - 192.168.0.24
  keyspace: 'temperatures'


